theme: jekyll-theme-tactile
google_analytics: UA-114571919-1
future: true
current-contribution-url: "https://github.com/modelica/newsletter/tree/main/_2023-03"
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/ModelicaLogoSq.jpg 
    author: modelica 
contribution-open: true
contribution-deadline: February 9, 2024
current-newsletter-date: November 14, 2023
baseurl: /
url: "https://newsletter.modelica.org"
collections:
  2018-01:
    permalink: /:collection/:path
    title: First release!
    output: true
  2018-02:
    permalink: /:collection/:path
    title: Summer release
    output: true
  2018-03:
    permalink: /:collection/:path
    title: Winter release
    output: true
  2019-01:
    permalink: /:collection/:path
    title: Spring 2019 release
    output: true
  2019-02:
    permalink: /:collection/:path
    title: Summer 2019 release
    output: true
  2019-03:
    permalink: /:collection/:path
    title: Fall 2019 release
    output: true
  2020-01:
    permalink: /:collection/:path
    title: Winter 2020 release
    output: true
  2020-02:
    permalink: /:collection/:path
    title: Summer 2020 release
    output: true
  2020-03:
    permalink: /:collection/:path
    title: Fall 2020 release
    output: true    
  2021-01:
    permalink: /:collection/:path
    title: Spring 2021 release
    output: true   
  2021-02:
    permalink: /:collection/:path
    title: Summer 2021 release
    output: true   
  2021-03:
    permalink: /:collection/:path
    title: Fall 2021 release
    output: true   
  2022-01:
    permalink: /:collection/:path
    title: Winter 2022 release
    output: true   
  2022-02:
    permalink: /:collection/:path
    title: Summer 2022 release prepared
    output: true   
  2022-03:
    permalink: /:collection/:path
    title: Fall 2022 release
    output: true   
  2023-01:
    permalink: /:collection/:path
    title: Spring 2023 release
    output: true   
  2023-02:
    permalink: /:collection/:path
    title: Summer 2023 release
    output: true
  2023-03:
    permalink: /:collection/:path
    title: Fall 2023 release
    output: true 
  2023-MC:
    permalink: /:collection/:path
    title: Modelica conference release
    output: true     
