theme: jekyll-theme-tactile
google_analytics: UA-114571919-1
current-contribution-url: "https://github.com/modelica/newsletter/tree/master/_2019-01"
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/ModelicaLogoSq.jpg 
    author: modelica 
contribution-open: false
contribution-deadline: 22 June
current-newsletter-date: 25 March
baseurl: /
url: "https://newsletter.modelica.org"
collections:
  2018-01:
    permalink: /:collection/:path
    title: First release!
    output: true
  2018-02:
    permalink: /:collection/:path
    title: Summer release
    output: true  
  2018-03:
    permalink: /:collection/:path
    title: Winter release
    output: true
  2019-01:
    permalink: /:collection/:path
    title: Spring 2019 release
    output: true    
